[
    {
        "bolge": "MARMARA",
        "sehir": "İSTANBUL",
        "plaka": 34,
        "ilceler": [
            "ADALAR",
            "ARNAVUTKÖY",
            "ATAŞEHİR",
            "AVCILAR",
            "BAĞCILAR",
            "BAHÇELİEVLER",
            "BAKIRKÖY",
            "BAŞAKŞEHİR",
            "BAYRAMPAŞA",
            "BEŞİKTAŞ",
            "BEYKOZ",
            "BEYLİKDÜZÜ",
            "BEYOĞLU",
            "BÜYÜKÇEKMECE",
            "ÇATALCA",
            "ÇEKMEKÖY",
            "ESENLER",
            "ESENYURT",
            "EYÜP",
            "FATİH",
            "GAZİOSMANPAŞA",
            "GÜNGÖREN",
            "KADIKÖY",
            "KAĞITHANE",
            "KARTAL",
            "KÜÇÜKÇEKMECE",
            "MALTEPE",
            "PENDİK",
            "SANCAKTEPE",
            "SARIYER",
            "SİLİVRİ",
            "SULTANBEYLİ",
            "SULTANGAZİ",
            "ŞİLE",
            "ŞİŞLİ",
            "TUZLA",
            "ÜMRANİYE",
            "ÜSKÜDAR",
            "ZEYTİNBURNU"
        ],
        "index": 0
    }
]
